Parameters:
  EnvSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select EnvSize (S,M,L)

  DatabaseName:
    Type: String
    Default: wordpress
  DatabaseUser:
    Type: String
    Default: wordpress
  DatabasePassword:
    Type: String
    Default: w0rdpr355
    NoEcho: true

Mappings:
  RegionMap:
    us-east-1 :
      "AMALINUX" : "ami-0922553b7b0369273"

  InstanceSize:
    SMALL:
      "EC2": "t2.micro"
      "DB": "db.t2.micro"
    MEDIUM:
      "EC2": "t2.nano"
      "DB": "db.t2.nano"
    LARGE:
      "EC2": "t2.small"
      "DB": "db.t2.small"

Resources:
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX]
      InstanceType: !FindInMap [InstanceSize, !Ref EnvSize, EC2]
      KeyName: psarz
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd php mysql php-mysql -y
            yum update -y
            chkconfig httpd on
            service httpd start
            cd /var/www/html
            wget https://wordpress.org/latest.tar.gz
            tar -zxvf latest.tar.gz --strip 1
            rm latest.tar.gz
            cp wp-config-sample.php wp-config.php
            sed -i 's/wordpress/${DatabaseName}/g' wp-config.php
            sed -i 's/####db-end-point###/${DB.Endpoint.Address}/g' wp-config.php
            sed -i 's/wordpress/${DatabaseUser}/g' wp-config.php
            sed -i 's/w0rdpr355/${DatabasePassword}/g' wp-config.php


  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvSize, DB]
      DBName: !Ref DatabaseName
      Engine: MySQL
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword

  S3:
    Type: "AWS::S3::Bucket"
